# Site settings
title: Joshua's Blog
email: joshuahouston@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog is about stuff.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jfact0ry.com" # the base hostname & protocol for your site
twitter_username: sleepyjoshua
github_username:  joshuahouston

# Build settings
markdown: kramdown
data_source: data
gems: ["jemoji"]
